<?php

/**
 * This file is part of the package magicsunday/webtrees-statistics.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use MagicSunday\Webtrees\Statistic\Statistic;

/**
 * @var string    $module    The name of the module
 * @var Tree      $tree      The current tree
 * @var Statistic $statistic
 */
?>
<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-3">
        <div class="col">
            <div class="card h-100">
                <?php
                    $birthsByMonth = $statistic->getBirthsByMonth();
$totalBirths                       = array_sum($birthsByMonth);
?>
                <div class="card-header">
                    <h5 class="card-title"><?php echo I18N::translate('Births by month'); ?></h5>
                    <small><?php echo I18N::plural('%s individual with a recorded birth month', '%s individuals with a recorded birth month', $totalBirths, I18N::number($totalBirths)); ?></small>
                </div>
                <div class="card-body">
                    <?php
        echo view(
            $module . '::modules/statistics-chart/Partials/ProgressList',
            [
                'class' => 'progress-births-month',
                'data'  => $birthsByMonth,
            ]
        );
?>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card h-100">
                <?php
$birthsByZodiacSign = $statistic->getBirthsByZodiacSign();
$totalBirths        = array_sum($birthsByZodiacSign);
?>
                <div class="card-header">
                    <h5 class="card-title"><?php echo I18N::translate('Births by zodiac sign'); ?></h5>
                    <small><?php echo I18N::plural('%s individual with a known zodiac sign', '%s individuals with a known zodiac sign', $totalBirths, I18N::number($totalBirths)); ?></small>
                </div>
                <div class="card-body">
                    <?php
        echo view(
            $module . '::modules/statistics-chart/Partials/ProgressList',
            [
                'class' => 'progress-births-zodiac',
                'data'  => $birthsByZodiacSign,
            ]
        );
?>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card h-100">
                <?php
$birthsByCentury = $statistic->getBirthsByCentury();
$totalBirths     = array_sum($birthsByCentury);
?>
                <div class="card-header">
                    <h5 class="card-title"><?php echo I18N::translate('Births by century'); ?></h5>
                    <small><?php echo I18N::plural('%s individual with a recorded birth year', '%s individuals with a recorded birth year', $totalBirths, I18N::number($totalBirths)); ?></small>
                </div>
                <div class="card-body">
                    <?php
        echo view(
            $module . '::modules/statistics-chart/Partials/ProgressList',
            [
                'class' => 'progress-births-century',
                'data'  => $birthsByCentury,
            ]
        );
?>
                </div>
            </div>
        </div>
    </div>
</div>
