<?php

/**
 * This file is part of the package magicsunday/webtrees-statistics.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use MagicSunday\Webtrees\Statistic\Statistic;

/**
 * @var string    $module    The name of the module
 * @var Tree      $tree      The current tree
 * @var Statistic $statistic
 */
?>

<style>

    body {
        --bs-progress-label-color: rgb(89, 89, 89);

        --bs-progress-label-gradient-start: white;
        --bs-progress-label-gradient-end: purple;
    }

    .card-title {
        font-weight: 600;
    }

    .card-body {
        text-align: center;
    }

    body {
        --bs-progress-bar-bg-births-month: rgb(255, 187, 131);
        --bs-progress-bar-bg-births-zodiac: rgb(156, 151, 255);
        --bs-progress-bar-bg-births-century: rgb(31, 102, 74);
    }

    .progress-births-month {
        background-color: var(--bs-progress-bar-bg-births-month) !important;
    }

    .progress-births-zodiac {
        background-color: var(--bs-progress-bar-bg-births-zodiac) !important;
    }

    .progress-births-century {
        background-color: var(--bs-progress-bar-bg-births-century) !important;
    }

</style>

<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-3">
        <div class="col">
            <div class="card h-100">
                <?php
                    $birthsByMonth = $statistic->getBirthsByMonth();
                    $totalBirths   = array_sum($birthsByMonth);
                ?>
                <div class="card-header">
                    <h5 class="card-title">Geburtsmonate</h5>
                    <small><?= I18N::number($totalBirths) ?> Personen mit Geburtsmonat</small>
                </div>
                <div class="card-body">
                    <?php
                        echo view(
                            $module . '::modules/statistics-chart/Partials/ProgressList',
                            [
                                'class' => 'progress-births-month',
                                'data'  => $birthsByMonth,
                            ]
                        );
                    ?>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card h-100">
                <?php
                    $birthsByZodiacSign = $statistic->getBirthsByZodiacSign();
                    $totalBirths        = array_sum($birthsByZodiacSign);
                ?>
                <div class="card-header">
                    <h5 class="card-title">Sternzeichen</h5>
                    <small><?= I18N::number($totalBirths) ?> Personen mit Sternzeichen</small>
                </div>
                <div class="card-body">
                    <?php
                        echo view(
                            $module . '::modules/statistics-chart/Partials/ProgressList',
                            [
                                'class' => 'progress-births-zodiac',
                                'data'  => $birthsByZodiacSign,
                            ]
                        );
                    ?>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card h-100">
                <?php
                    $birthsByCentury = $statistic->getBirthsByCentury();
                    $totalBirths     = array_sum($birthsByCentury);
                ?>
                <div class="card-header">
                    <h5 class="card-title">Geburtsstatistik nach Jahrhundert</h5>
                    <small><?= I18N::number($totalBirths) ?> Personen mit Geburtsjahr</small>
                </div>
                <div class="card-body">
                    <?php
                        echo view(
                            $module . '::modules/statistics-chart/Partials/ProgressList',
                            [
                                'class' => 'progress-births-century',
                                'data'  => $birthsByCentury,
                            ]
                        );
                    ?>
                </div>
            </div>
        </div>
    </div>
</div>
