<?php

/**
 * This file is part of the package magicsunday/webtrees-statistics.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use MagicSunday\Webtrees\Statistic\Statistic;

/**
 * @var string    $module    The name of the module
 * @var Tree      $tree      The current tree
 * @var Statistic $statistic
 */
?>
<div class="container">
    <div class="row row-cols-1 row-cols-md-2 g-3">
        <div class="col">
            <div class="card h-100">
                <?php
                    $deathsByMonth = $statistic->getDeathsByMonth();
$totalDeaths                       = array_sum($deathsByMonth);
?>
                <div class="card-header">
                    <h5 class="card-title"><?php echo I18N::translate('Deaths by month'); ?></h5>
                    <small><?php echo I18N::plural('%s individual with a recorded death month', '%s individuals with a recorded death month', $totalDeaths, I18N::number($totalDeaths)); ?></small>
                </div>
                <div class="card-body">
                    <?php
        echo view(
            $module . '::modules/statistics-chart/Partials/ProgressList',
            [
                'class' => 'progress-deaths-month',
                'data'  => $deathsByMonth,
            ]
        );
?>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card h-100">
                <?php
$deathsByCentury = $statistic->getDeathsByCentury();
$totalDeaths     = array_sum($deathsByCentury);
?>
                <div class="card-header">
                    <h5 class="card-title"><?php echo I18N::translate('Deaths by century'); ?></h5>
                    <small><?php echo I18N::plural('%s individual with a recorded death year', '%s individuals with a recorded death year', $totalDeaths, I18N::number($totalDeaths)); ?></small>
                </div>
                <div class="card-body">
                    <?php
        echo view(
            $module . '::modules/statistics-chart/Partials/ProgressList',
            [
                'class' => 'progress-deaths-century',
                'data'  => $deathsByCentury,
            ]
        );
?>
                </div>
            </div>
        </div>
    </div>
</div>
