<?php

declare(strict_types=1);

/**
 * This file is part of the package magicsunday/webtrees-statistics.
 *
 * For the full copyright and license information, please read the
 * LICENSE file that was distributed with this source code.
 */

use Fisharebest\Webtrees\I18N;
use MagicSunday\Webtrees\Statistic\Statistic;

/**
 * @var string    $module    The name of the module
 * @var Statistic $statistic
 */
?>
<div class="container">
    <div class="row row-cols-1 row-cols-lg-3 g-3">
        <div class="col">
            <div class="card h-100">
                <div class="card-header">
                    <h5 class="card-title"><?php echo I18N::translate('Common surnames'); ?></h5>
                    <small><?php echo I18N::translate('%s distinct surnames (top 15 shown)', I18N::number($statistic->getTotalSurnames())); ?></small>
                </div>
                <div class="card-body">
                    <?php
                        echo view(
                            $module . '::modules/statistics-chart/Partials/TagCloud',
                            [
                                'data' => $statistic->getTopSurnames(15),
                            ],
                        );
?>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card h-100">
                <div class="card-header">
                    <h5 class="card-title"><?php echo I18N::translate('Common given names – male'); ?></h5>
                    <small><?php echo I18N::translate('%s distinct male given names (top 15 shown)', I18N::number($statistic->getTotalMaleGivenNames())); ?></small>
                </div>
                <div class="card-body">
                    <?php
    echo view(
        $module . '::modules/statistics-chart/Partials/TagCloud',
        [
            'data' => $statistic->getTopMaleGivenNames(15),
        ],
    );
?>
                </div>
            </div>
        </div>

        <div class="col">
            <div class="card h-100">
                <div class="card-header">
                    <h5 class="card-title"><?php echo I18N::translate('Common given names – female'); ?></h5>
                    <small><?php echo I18N::translate('%s distinct female given names (top 15 shown)', I18N::number($statistic->getTotalFemaleGivenNames())); ?></small>
                </div>
                <div class="card-body">
                    <?php
    echo view(
        $module . '::modules/statistics-chart/Partials/TagCloud',
        [
            'data' => $statistic->getTopFemaleGivenNames(15),
        ],
    );
?>
                </div>
            </div>
        </div>
    </div>
</div>
