<?php

/**
 * This file is part of the package magicsunday/webtrees-statistics.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;
use MagicSunday\Webtrees\Statistic\Statistic;

/**
 * @var string    $module    The name of the module
 * @var Statistic $statistic
 */
?>
<div class="container">
    <div class="row row-cols-1 row-cols-md-1 g-3">
        <div class="col" data-map-type="birth">
            <div class="card h-100">
                <?php
                    $birthsByCountry = $statistic->getBirthsByCountry();
$totalBirths                         = array_sum(array_column($birthsByCountry, 'count'));
?>
                <div class="card-header">
                    <h5 class="card-title"><?php echo I18N::translate('Place of birth'); ?></h5>
                    <small><?php echo I18N::plural('%s recorded country of birth', '%s recorded countries of birth', $totalBirths, I18N::number($totalBirths)); ?></small>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3">
                            <?php
                $progressList = [];

foreach ($birthsByCountry as $values) {
    $progressList[$values['label']] = $values['count'];
}

echo view(
    $module . '::modules/statistics-chart/Partials/ProgressList',
    [
        'class' => 'progress-births-country',
        'data'  => array_slice($progressList, 0, 10),
    ]
);
?>
                        </div>
                        <div class="col-md-9 mt-3 mt-md-0">
                            <?php
    echo view(
        $module . '::modules/statistics-chart/Partials/GeoMap',
        [
            'identifier' => 'living-geo-map',
            'class'      => '',
            'data'       => $birthsByCountry,
        ]
    );
?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col" data-map-type="death">
            <div class="card h-100">
                <?php
                    $deathsByCountry = $statistic->getDeathsByCountry();
$totalDeaths                         = array_sum(array_column($deathsByCountry, 'count'));
?>
                <div class="card-header">
                    <h5 class="card-title"><?php echo I18N::translate('Place of death'); ?></h5>
                    <small><?php echo I18N::plural('%s recorded country of death', '%s recorded countries of death', $totalDeaths, I18N::number($totalDeaths)); ?></small>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-3">
                            <?php
                $progressList = [];

foreach ($deathsByCountry as $values) {
    $progressList[$values['label']] = $values['count'];
}

echo view(
    $module . '::modules/statistics-chart/Partials/ProgressList',
    [
        'class' => 'progress-deaths-country',
        'data'  => array_slice($progressList, 0, 10),
    ]
);
?>
                        </div>
                        <div class="col-md-9 mt-3 mt-md-0">
                            <?php
    echo view(
        $module . '::modules/statistics-chart/Partials/GeoMap',
        [
            'identifier' => 'deaths-geo-map',
            'class'      => '',
            'data'       => $deathsByCountry,
        ]
    );
?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
