<?php

/**
 * This file is part of the package magicsunday/webtrees-statistics.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

/**
 * @var string $identifier
 * @var array  $data
 */
?>
<div class="donut-chart-container">
    <div id="<?php echo $identifier; ?>" class="donut-chart"></div>

    <table class="legend">
        <?php foreach ($data as $entry) { ?>
            <tr>
                <td>
                    <span class="dot<?php echo isset($entry['class']) ? (' ' . $entry['class']) : ''; ?>"
                        <?php echo isset($entry['fill']) ? (' style="background-color: ' . $entry['fill'] . ';"') : ''; ?>
                    ></span>
                </td>
                <td><?php echo $entry['label']; ?></td>
                <td><?php echo I18N::number($entry['value']); ?></td>
            </tr>
        <?php } ?>
    </table>
</div>

<script>

webtreesStatistics.draw(
    <?php echo json_encode($identifier, JSON_THROW_ON_ERROR); ?>,
    <?php echo json_encode($data, JSON_THROW_ON_ERROR); ?>,
    {
        type: "donut",

        // width: 500,
        // height: 400,

        // margin: 10,

        holeSize: 90
    }
)

</script>

