<?php

/**
 * This file is part of the package magicsunday/webtrees-statistics.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\I18N;

/**
 * @var string                                                                      $identifier Host element id
 * @var array<int, array{label: string, value: int, class?: string, fill?: string}> $data Slice payload
 */
?>
<div class="donut-chart-container">
    <div id="<?php echo e($identifier); ?>"
         class="donut-chart"
         data-widget="donut"
         data-payload="<?php echo e(json_encode($data, JSON_THROW_ON_ERROR)); ?>"
         data-options="<?php echo e(json_encode(['holeSize' => 90, 'width' => 250, 'height' => 250], JSON_THROW_ON_ERROR)); ?>"
    ></div>

    <table class="legend">
        <?php foreach ($data as $entry) { ?>
            <tr>
                <td>
                    <span class="dot<?php echo isset($entry['class']) ? (' ' . e($entry['class'])) : ''; ?>"
                        <?php echo isset($entry['fill']) ? (' style="background-color: ' . e($entry['fill']) . ';"') : ''; ?>
                    ></span>
                </td>
                <td><?php echo e($entry['label']); ?></td>
                <td><?php echo I18N::number($entry['value']); ?></td>
            </tr>
        <?php } ?>
    </table>
</div>
