<?php

/**
 * This file is part of the package magicsunday/webtrees-statistics.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\Tree;

/**
 * @var string                                                            $identifier Host element id
 * @var Tree                                                              $tree
 * @var array<int, array{countryCode: string, label: string, count: int}> $data
 */
?>
<div class="world-map-container"
     data-widget="world-map"
     data-payload="<?php echo e(json_encode($data, JSON_THROW_ON_ERROR)); ?>"
     data-options="<?php echo e(json_encode(['width' => 900, 'height' => 510], JSON_THROW_ON_ERROR)); ?>"
>
    <div id="<?php echo e($identifier); ?>" class="world-map"></div>
</div>
