<?php

/**
 * This file is part of the package magicsunday/webtrees-statistics.
 *
 * For the full copyright and license information, please read the
 * LICENSE file distributed with this source code.
 */

declare(strict_types=1);

use Fisharebest\Webtrees\Tree;

/**
 * @var Tree               $tree
 * @var array<string, int> $data
 * @var string             $class
 */
?>

<style>

    .progress-bar-table {
        border-collapse: collapse;
        border-spacing: 0;
        width: 100%;
    }

    .progress-bar-table .label {
        color: var(--bs-progress-label-color);
        text-align: left;
        font-weight: 400;
    }

    .progress-bar-table .value {
        color: var(--bs-progress-label-color);
        text-align: right;
        font-weight: 400;
    }

    .progress-bar-table .progress-bar {
        border-radius: var(--bs-progress-border-radius);
    }

</style>

<div class="wt-births-list">
    <table class="progress-bar-table">
        <tbody>
            <?php $maximum = ($data === []) ? 0 : max($data); ?>
            <?php foreach ($data as $key => $value) { ?>
                <?php $width = ($maximum > 0) ? ($value * 100.0 / $maximum) : 0.0; ?>

                <tr>
                    <td class="label"><small><?php echo $key; ?></small></td>
                    <td class="value"><small><?php echo $value; ?></small></td>
                </tr>
                <tr>
                    <td colspan="2" class="pb-2">
                        <div class="progress" role="progressbar"
                             aria-label="<?php echo $key; ?>"
                             aria-valuenow="<?php echo $width; ?>"
                             aria-valuemin="0"
                             aria-valuemax="100"
                             style="height: 16px;"
                        >
                            <div class="progress-bar <?php echo $class; ?>" style="width: calc(16px + <?php echo $width; ?>%); background-color: color-mix(in srgb, var(--bs-progress-label-gradient-start), var(--bs-progress-label-gradient-end) <?php echo $width; ?>%)"></div>
                        </div>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
