<?php

declare(strict_types=1);

/**
 * This file is part of the package magicsunday/webtrees-statistics.
 *
 * For the full copyright and license information, please read the
 * LICENSE file that was distributed with this source code.
 */

use Fisharebest\Webtrees\I18N;
use MagicSunday\Webtrees\Statistic\Model\Dto\Tree\TreeRecordsReport;

/**
 * @var TreeRecordsReport $treeRecords Aggregated record-holders across the tree
 */
?>
<table class="table table-sm wt-records-table mb-0">
    <tbody>
        <?php if ($treeRecords->oldestDeceased !== null) { ?>
            <tr>
                <th scope="row"><?php echo I18N::translate('Oldest deceased'); ?></th>
                <td><?php echo I18N::plural('%s year', '%s years', $treeRecords->oldestDeceased->ageYears, I18N::number($treeRecords->oldestDeceased->ageYears)); ?></td>
                <td><a href="<?php echo e($treeRecords->oldestDeceased->individual->url()); ?>"><?php echo $treeRecords->oldestDeceased->individual->fullName(); ?></a></td>
            </tr>
        <?php } ?>
        <?php if ($treeRecords->oldestLiving !== null) { ?>
            <tr>
                <th scope="row"><?php echo I18N::translate('Oldest living'); ?></th>
                <td><?php echo I18N::plural('%s year', '%s years', $treeRecords->oldestLiving->ageYears, I18N::number($treeRecords->oldestLiving->ageYears)); ?></td>
                <td><a href="<?php echo e($treeRecords->oldestLiving->individual->url()); ?>"><?php echo $treeRecords->oldestLiving->individual->fullName(); ?></a></td>
            </tr>
        <?php } ?>
        <?php if ($treeRecords->longestMarriage !== null) { ?>
            <tr>
                <th scope="row"><?php echo I18N::translate('Longest marriage'); ?></th>
                <td><?php echo I18N::plural('%s year', '%s years', $treeRecords->longestMarriage->durationYears, I18N::number($treeRecords->longestMarriage->durationYears)); ?></td>
                <td><a href="<?php echo e($treeRecords->longestMarriage->family->url()); ?>"><?php echo $treeRecords->longestMarriage->family->fullName(); ?></a></td>
            </tr>
        <?php } ?>
        <?php if ($treeRecords->shortestMarriage !== null) { ?>
            <tr>
                <th scope="row"><?php echo I18N::translate('Shortest marriage'); ?></th>
                <td><?php echo I18N::plural('%s day', '%s days', $treeRecords->shortestMarriage->durationDays, I18N::number($treeRecords->shortestMarriage->durationDays)); ?></td>
                <td><a href="<?php echo e($treeRecords->shortestMarriage->family->url()); ?>"><?php echo $treeRecords->shortestMarriage->family->fullName(); ?></a></td>
            </tr>
        <?php } ?>
        <?php if ($treeRecords->youngestHusband !== null) { ?>
            <tr>
                <th scope="row"><?php echo I18N::translate('Youngest husband at marriage'); ?></th>
                <td><?php echo I18N::plural('%s year', '%s years', $treeRecords->youngestHusband->ageYears, I18N::number($treeRecords->youngestHusband->ageYears)); ?></td>
                <td><a href="<?php echo e($treeRecords->youngestHusband->individual->url()); ?>"><?php echo $treeRecords->youngestHusband->individual->fullName(); ?></a></td>
            </tr>
        <?php } ?>
        <?php if ($treeRecords->youngestWife !== null) { ?>
            <tr>
                <th scope="row"><?php echo I18N::translate('Youngest wife at marriage'); ?></th>
                <td><?php echo I18N::plural('%s year', '%s years', $treeRecords->youngestWife->ageYears, I18N::number($treeRecords->youngestWife->ageYears)); ?></td>
                <td><a href="<?php echo e($treeRecords->youngestWife->individual->url()); ?>"><?php echo $treeRecords->youngestWife->individual->fullName(); ?></a></td>
            </tr>
        <?php } ?>
        <?php if ($treeRecords->oldestHusband !== null) { ?>
            <tr>
                <th scope="row"><?php echo I18N::translate('Oldest husband at marriage'); ?></th>
                <td><?php echo I18N::plural('%s year', '%s years', $treeRecords->oldestHusband->ageYears, I18N::number($treeRecords->oldestHusband->ageYears)); ?></td>
                <td><a href="<?php echo e($treeRecords->oldestHusband->individual->url()); ?>"><?php echo $treeRecords->oldestHusband->individual->fullName(); ?></a></td>
            </tr>
        <?php } ?>
        <?php if ($treeRecords->oldestWife !== null) { ?>
            <tr>
                <th scope="row"><?php echo I18N::translate('Oldest wife at marriage'); ?></th>
                <td><?php echo I18N::plural('%s year', '%s years', $treeRecords->oldestWife->ageYears, I18N::number($treeRecords->oldestWife->ageYears)); ?></td>
                <td><a href="<?php echo e($treeRecords->oldestWife->individual->url()); ?>"><?php echo $treeRecords->oldestWife->individual->fullName(); ?></a></td>
            </tr>
        <?php } ?>
        <?php if ($treeRecords->mostSpouses !== null) { ?>
            <tr>
                <th scope="row"><?php echo I18N::translate('Most spouses'); ?></th>
                <td><?php echo I18N::plural('%s spouse', '%s spouses', $treeRecords->mostSpouses->count, I18N::number($treeRecords->mostSpouses->count)); ?></td>
                <td><a href="<?php echo e($treeRecords->mostSpouses->individual->url()); ?>"><?php echo $treeRecords->mostSpouses->individual->fullName(); ?></a></td>
            </tr>
        <?php } ?>
        <?php if ($treeRecords->largestFamily !== null) { ?>
            <tr>
                <th scope="row"><?php echo I18N::translate('Largest family'); ?></th>
                <td><?php echo I18N::plural('%s child', '%s children', $treeRecords->largestFamily->count, I18N::number($treeRecords->largestFamily->count)); ?></td>
                <td><a href="<?php echo e($treeRecords->largestFamily->family->url()); ?>"><?php echo $treeRecords->largestFamily->family->fullName(); ?></a></td>
            </tr>
        <?php } ?>
        <?php if ($treeRecords->mostChildrenPerPerson !== null) { ?>
            <tr>
                <th scope="row"><?php echo I18N::translate('Most children per person'); ?></th>
                <td><?php echo I18N::plural('%s child', '%s children', $treeRecords->mostChildrenPerPerson->count, I18N::number($treeRecords->mostChildrenPerPerson->count)); ?></td>
                <td><a href="<?php echo e($treeRecords->mostChildrenPerPerson->individual->url()); ?>"><?php echo $treeRecords->mostChildrenPerPerson->individual->fullName(); ?></a></td>
            </tr>
        <?php } ?>
        <?php if ($treeRecords->youngestFatherAtFirstChild !== null) { ?>
            <tr>
                <th scope="row"><?php echo I18N::translate('Youngest father at first child'); ?></th>
                <td><?php echo I18N::plural('%s year', '%s years', $treeRecords->youngestFatherAtFirstChild->ageYears, I18N::number($treeRecords->youngestFatherAtFirstChild->ageYears)); ?></td>
                <td><a href="<?php echo e($treeRecords->youngestFatherAtFirstChild->individual->url()); ?>"><?php echo $treeRecords->youngestFatherAtFirstChild->individual->fullName(); ?></a></td>
            </tr>
        <?php } ?>
        <?php if ($treeRecords->youngestMotherAtFirstChild !== null) { ?>
            <tr>
                <th scope="row"><?php echo I18N::translate('Youngest mother at first child'); ?></th>
                <td><?php echo I18N::plural('%s year', '%s years', $treeRecords->youngestMotherAtFirstChild->ageYears, I18N::number($treeRecords->youngestMotherAtFirstChild->ageYears)); ?></td>
                <td><a href="<?php echo e($treeRecords->youngestMotherAtFirstChild->individual->url()); ?>"><?php echo $treeRecords->youngestMotherAtFirstChild->individual->fullName(); ?></a></td>
            </tr>
        <?php } ?>
        <?php if ($treeRecords->oldestFatherAtFirstChild !== null) { ?>
            <tr>
                <th scope="row"><?php echo I18N::translate('Oldest father at first child'); ?></th>
                <td><?php echo I18N::plural('%s year', '%s years', $treeRecords->oldestFatherAtFirstChild->ageYears, I18N::number($treeRecords->oldestFatherAtFirstChild->ageYears)); ?></td>
                <td><a href="<?php echo e($treeRecords->oldestFatherAtFirstChild->individual->url()); ?>"><?php echo $treeRecords->oldestFatherAtFirstChild->individual->fullName(); ?></a></td>
            </tr>
        <?php } ?>
        <?php if ($treeRecords->oldestMotherAtFirstChild !== null) { ?>
            <tr>
                <th scope="row"><?php echo I18N::translate('Oldest mother at first child'); ?></th>
                <td><?php echo I18N::plural('%s year', '%s years', $treeRecords->oldestMotherAtFirstChild->ageYears, I18N::number($treeRecords->oldestMotherAtFirstChild->ageYears)); ?></td>
                <td><a href="<?php echo e($treeRecords->oldestMotherAtFirstChild->individual->url()); ?>"><?php echo $treeRecords->oldestMotherAtFirstChild->individual->fullName(); ?></a></td>
            </tr>
        <?php } ?>
    </tbody>
</table>
