<?php

declare(strict_types=1);

/**
 * This file is part of the package magicsunday/webtrees-statistics.
 *
 * For the full copyright and license information, please read the
 * LICENSE file that was distributed with this source code.
 */

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Individual;

/**
 * @var array<array{label: string, value: int}> $data
 */
$maximum = max(array_map(static fn (array $x): int => $x['value'], $data));
$minimum = min(array_map(static fn (array $x): int => $x['value'], $data));
?>
<div class="wt-surnames-tag-cloud">
    <?php foreach ($data as $entry) { ?>
        <?php
            $size = $maximum === $minimum ? 0.8 : 0.8 + (1.2 * ($entry['value'] - $minimum) / ($maximum - $minimum));

        if ($entry['label'] === Individual::NOMEN_NESCIO) {
            $label = I18N::translateContext('Unknown surname', '…');
        } else {
            $label = e($entry['label']);
        }
        ?>
        <span class="tag text-nowrap ut p-1" style="font-size:<?php echo $size; ?>rem" dir="auto" title="<?php echo e(I18N::plural('%s individual carries this name', '%s individuals carry this name', $entry['value'], I18N::number($entry['value']))); ?>"><?php echo $label; ?></span>
    <?php } ?>
</div>
